# Generated by Django 4.2.4 on 2024-01-10 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('limite_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('intervalo_tempo', models.PositiveIntegerField(default=60)),
                ('monitorar', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
