# Generated by Django 4.2.9 on 2024-01-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='intervalo_tempo',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='limite_compra',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='limite_venda',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ativo',
            name='abertura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativo',
            name='cotacao',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativo',
            name='fechamento',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativo',
            name='variacao_percentual',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ativo',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
