# Generated by Django 4.2.9 on 2024-01-12 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ativos', '0002_remove_ativo_intervalo_tempo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='monitorar',
        ),
        migrations.AddField(
            model_name='ativo',
            name='usuarios_monitorando',
            field=models.ManyToManyField(related_name='ativos_monitorados', to=settings.AUTH_USER_MODEL),
        ),
    ]
