# Generated by Django 4.2.9 on 2024-01-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_remove_ativo_monitorar_ativo_usuarios_monitorando'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='limiar_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='limiar_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='limite_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='limite_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
