# Generated by Django 4.2.9 on 2024-01-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0006_alter_ativo_cotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='frequencia_monitoramento',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='ativo',
            name='ultimo_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
