# Generated by Django 4.2.9 on 2024-01-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0007_ativo_frequencia_monitoramento_ativo_ultimo_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='frequencia_monitoramento',
            field=models.IntegerField(default=2),
        ),
    ]
